name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_PASSWORD }}
    - name: Build the Docker image
      run: |
        currImage="rockclimber81/mariadb-backup:$(date +%s)"
        docker build . --file Dockerfile --tag $currImage
        docker push $currImage
        docker logout
